#!/usr/bin/env bash
set -euo pipefail

mkdir -p videos

read -ra URL_LIST <<< "${VIDEO_URLS}"
if [ ${#URL_LIST[@]} -eq 0 ]; then
  echo "No URLs provided"
  exit 1
fi

SPLIT_BYTES=$(( SPLIT_MB * 1024 * 1024 ))
FORMAT="bestvideo[height<=${QUALITY}]+bestaudio/best[height<=${QUALITY}]/best"

sanitize_name() {
  echo "$1" | sed 's/[[:space:]]\+/-/g' | tr -cd '[:alnum:]_.-'
}

urlencode() {
  python3 -c "import urllib.parse,sys;print(urllib.parse.quote(sys.argv[1],safe=''))" "$1"
}

regenerate_master_readme() {
  local master="videos/README.md"
  {
    echo "# Downloaded Videos"
    echo
    echo "Generated by workflow on $(date -u +'%Y-%m-%d %H:%M:%S UTC')"
    echo
  } > "$master"

  local n=0
  for folder in videos/*/; do
    [ -d "$folder" ] || continue
    [ -f "$folder/README.md" ] || continue
    n=$((n+1))
    local name
    name=$(basename "$folder")
    echo "- ${n}. [${name}](./${name}/README.md)" >> "$master"
  done
}

index=0
for url in "${URL_LIST[@]}"; do
  index=$((index+1))
  tmp="/tmp/mood_dl_${index}"
  rm -rf "$tmp"
  mkdir -p "$tmp"

  yt-dlp \
    --format "$FORMAT" \
    --merge-output-format mp4 \
    --write-thumbnail \
    --convert-thumbnails jpg \
    --no-playlist \
    --output "$tmp/%(title)s.%(ext)s" \
    "$url"

  find "$tmp" -name '*.part' -delete

  for f in "$tmp"/*; do
    [ -f "$f" ] || continue
    case "$f" in
      *.jpg|*.webp) continue ;;
    esac

    base=$(basename "$f")
    name="${base%.*}"
    ext="${base##*.}"
    safe_name=$(sanitize_name "$name")
    out_dir="videos/${safe_name}"
    suffix=1
    while [ -d "$out_dir" ]; do
      out_dir="videos/${safe_name}_${suffix}"
      suffix=$((suffix+1))
    done
    mkdir -p "$out_dir"

    thumb=$(find "$tmp" -maxdepth 1 -type f -name '*.jpg' | head -1 || true)
    if [ -n "$thumb" ] && [ -f "$thumb" ]; then
      cp "$thumb" "$out_dir/thumbnail.jpg"
    fi

    size=$(stat -c%s "$f")
    folder_name=$(basename "$out_dir")
    folder_encoded=$(urlencode "$folder_name")

    if [ "$size" -gt "$SPLIT_BYTES" ]; then
      archive_base="$out_dir/${folder_name}"
      zip -0 -s "${SPLIT_MB}m" "${archive_base}.zip" "$f"

      parts=("$out_dir"/*.z* "$out_dir"/*.zip)
      part_count=0
      total=0
      links=""
      i=0
      for p in "${parts[@]}"; do
        [ -f "$p" ] || continue
        i=$((i+1))
        part_count=$((part_count+1))
        psize=$(stat -c%s "$p")
        total=$((total+psize))
        pbase=$(basename "$p")
        pencoded=$(urlencode "$pbase")
        raw="https://raw.githubusercontent.com/${REPO_OWNER}/${REPO_NAME}/${BRANCH}/videos/${folder_encoded}/${pencoded}"
        links+="| ${i} | \`${pbase}\` | [Download](${raw}) |\n"
      done
      total_mb=$(echo "scale=2; $total/1024/1024" | bc)

      {
        echo "# ${name}"
        echo
        echo "| Property | Value |"
        echo "|---|---|"
        echo "| Source URL | ${url} |"
        echo "| Quality | ${QUALITY}p |"
        echo "| Package | ${part_count} parts (${total_mb} MB) |"
        echo
        echo "| # | File | Link |"
        echo "|---|---|---|"
        printf "%b" "$links"
      } > "$out_dir/README.md"
    else
      cp "$f" "$out_dir/${folder_name}.${ext}"
      size_mb=$(echo "scale=2; $size/1024/1024" | bc)
      file_encoded=$(urlencode "${folder_name}.${ext}")
      raw="https://raw.githubusercontent.com/${REPO_OWNER}/${REPO_NAME}/${BRANCH}/videos/${folder_encoded}/${file_encoded}"

      {
        echo "# ${name}"
        echo
        echo "| Property | Value |"
        echo "|---|---|"
        echo "| Source URL | ${url} |"
        echo "| Quality | ${QUALITY}p |"
        echo "| Size | ${size_mb} MB |"
        echo
        echo "| # | File | Link |"
        echo "|---|---|---|"
        echo "| 1 | \`${folder_name}.${ext}\` | [Download](${raw}) |"
      } > "$out_dir/README.md"
    fi
  done

  rm -rf "$tmp"
done

regenerate_master_readme
