#!/usr/bin/env bash
set -euo pipefail

mkdir -p videos

read -ra URL_LIST <<< "${VIDEO_URLS}"
if [ ${#URL_LIST[@]} -eq 0 ]; then
  echo "No URLs provided"
  exit 1
fi

SPLIT_BYTES=$(( SPLIT_MB * 1024 * 1024 ))
FORMAT="bestvideo[height<=${QUALITY}]+bestaudio/best[height<=${QUALITY}]/best"
COMMON_FLAGS=(
  --format "$FORMAT"
  --merge-output-format mp4
  --write-thumbnail
  --convert-thumbnails jpg
  --no-playlist
  --no-part
  --retries 5
  --fragment-retries 5
  --output "%(title)s.%(ext)s"
)

sanitize_name() {
  echo "$1" | sed 's/[[:space:]]\+/-/g' | tr -cd '[:alnum:]_.-'
}

urlencode() {
  python3 -c "import urllib.parse,sys;print(urllib.parse.quote(sys.argv[1],safe=''))" "$1"
}

normalize_youtube_url() {
  local input="$1"
  if [[ "$input" =~ youtu\.be/([a-zA-Z0-9_-]+) ]]; then
    local id="${BASH_REMATCH[1]}"
    id="${id%%\?*}"
    echo "https://www.youtube.com/watch?v=${id}"
  else
    echo "$input"
  fi
}

regenerate_master_readme() {
  local master="videos/README.md"
  {
    echo "# Downloaded Videos"
    echo
    echo "Generated by workflow on $(date -u +'%Y-%m-%d %H:%M:%S UTC')"
    echo
  } > "$master"

  local n=0
  for folder in videos/*/; do
    [ -d "$folder" ] || continue
    [ -f "$folder/README.md" ] || continue
    n=$((n+1))
    local name
    name=$(basename "$folder")
    echo "- ${n}. [${name}](./${name}/README.md)" >> "$master"
  done
}

download_video() {
  local url="$1"
  local tmp_dir="$2"

  pushd "$tmp_dir" >/dev/null

  local methods=(
    "--extractor-args youtube:player_client=web --js-runtimes deno --remote-components ejs:github"
    "--extractor-args youtube:player_client=web,mweb,android --js-runtimes deno --remote-components ejs:npm"
    "--extractor-args youtube:player_client=mweb --js-runtimes deno"
    "--extractor-args youtube:player_client=android"
  )

  local ok=1
  for method in "${methods[@]}"; do
    echo "Trying yt-dlp method: $method"
    if yt-dlp "${COMMON_FLAGS[@]}" --newline --progress ${method} "$url"; then
      ok=0
      break
    fi
    sleep 2
  done

  popd >/dev/null
  return $ok
}

index=0
success_count=0
for raw_url in "${URL_LIST[@]}"; do
  index=$((index+1))
  url=$(normalize_youtube_url "$raw_url")
  tmp="/tmp/mood_dl_${index}"
  rm -rf "$tmp"
  mkdir -p "$tmp"

  if ! download_video "$url" "$tmp"; then
    echo "Failed to download URL after all methods: $url"
    rm -rf "$tmp"
    continue
  fi

  success_count=$((success_count+1))
  find "$tmp" -name '*.part' -delete

  for f in "$tmp"/*; do
    [ -f "$f" ] || continue
    case "$f" in
      *.jpg|*.webp) continue ;;
    esac

    base=$(basename "$f")
    name="${base%.*}"
    ext="${base##*.}"
    safe_name=$(sanitize_name "$name")
    out_dir="videos/${safe_name}"
    suffix=1
    while [ -d "$out_dir" ]; do
      out_dir="videos/${safe_name}_${suffix}"
      suffix=$((suffix+1))
    done
    mkdir -p "$out_dir"

    thumb=$(find "$tmp" -maxdepth 1 -type f -name '*.jpg' | head -1 || true)
    if [ -n "$thumb" ] && [ -f "$thumb" ]; then
      cp "$thumb" "$out_dir/thumbnail.jpg"
    fi

    size=$(stat -c%s "$f")
    folder_name=$(basename "$out_dir")
    folder_encoded=$(urlencode "$folder_name")

    if [ "$size" -gt "$SPLIT_BYTES" ]; then
      archive_base="$out_dir/${folder_name}"
      zip -0 -s "${SPLIT_MB}m" "${archive_base}.zip" "$f"

      parts=("$out_dir"/*.z* "$out_dir"/*.zip)
      part_count=0
      total=0
      links=""
      i=0
      for p in "${parts[@]}"; do
        [ -f "$p" ] || continue
        i=$((i+1))
        part_count=$((part_count+1))
        psize=$(stat -c%s "$p")
        total=$((total+psize))
        pbase=$(basename "$p")
        pencoded=$(urlencode "$pbase")
        raw="https://raw.githubusercontent.com/${REPO_OWNER}/${REPO_NAME}/${BRANCH}/videos/${folder_encoded}/${pencoded}"
        links+="| ${i} | \`${pbase}\` | [Download](${raw}) |\n"
      done
      total_mb=$(echo "scale=2; $total/1024/1024" | bc)

      {
        echo "# ${name}"
        echo
        echo "| Property | Value |"
        echo "|---|---|"
        echo "| Source URL | ${url} |"
        echo "| Quality | ${QUALITY}p |"
        echo "| Package | ${part_count} parts (${total_mb} MB) |"
        echo
        echo "| # | File | Link |"
        echo "|---|---|---|"
        printf "%b" "$links"
      } > "$out_dir/README.md"
    else
      cp "$f" "$out_dir/${folder_name}.${ext}"
      size_mb=$(echo "scale=2; $size/1024/1024" | bc)
      file_encoded=$(urlencode "${folder_name}.${ext}")
      raw="https://raw.githubusercontent.com/${REPO_OWNER}/${REPO_NAME}/${BRANCH}/videos/${folder_encoded}/${file_encoded}"

      {
        echo "# ${name}"
        echo
        echo "| Property | Value |"
        echo "|---|---|"
        echo "| Source URL | ${url} |"
        echo "| Quality | ${QUALITY}p |"
        echo "| Size | ${size_mb} MB |"
        echo
        echo "| # | File | Link |"
        echo "|---|---|---|"
        echo "| 1 | \`${folder_name}.${ext}\` | [Download](${raw}) |"
      } > "$out_dir/README.md"
    fi
  done

  rm -rf "$tmp"
done

if [ "$success_count" -eq 0 ]; then
  echo "All URLs failed to download. For bot checks, use cookies with yt-dlp if needed."
  exit 1
fi

regenerate_master_readme
